bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6053118
  object_id: 60968aa2-8ecc-4ad3-46c2-15ab6fc16174
  sha: sha256:cfbfb8f888857c47c4cfde1ec37464b9ea9e80834fc96bb233d1af60ffc8d519
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5880389
  object_id: 51eb8c25-8f76-4831-7559-146ed35cf2e0
  sha: sha256:d03a45a5fd3287cea0bbfeb595a35159461e8f3c9e617462d7a1994c20924037
