bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070148
  object_id: 2861dd53-1620-4569-7c07-e44085fbb6ee
  sha: sha256:719c62e435b360f0f399f684a9cdf75abc7096e3235b3a6730a77fffc13b8a95
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5897771
  object_id: 96e2dd4a-43f1-4d58-5739-befa91f45c08
  sha: sha256:4e4ae6988effe57cc0eea189d62c7093cf9422496981bb0fabe70fda57df6c1a
