bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070133
  object_id: 845b844b-9883-42a5-6a61-6c37687c0393
  sha: sha256:b5ab99d5802b76e32bae64b23f90ebd1a58ac1b4fb29a894ae602b5ea69f48e7
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5897777
  object_id: b3e1e14f-9cd7-46f3-6ec6-499d617500c3
  sha: sha256:5384c53df77614ca08038d665a01025429c873af070e156a7c86dec4cff9e3e1
