bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070311
  object_id: 25a9bb85-fe71-4223-73f0-22b6ab402020
  sha: sha256:441701377868a5438bab308d2c3ef3688d59bec79019c15db1e3e719f423b435
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5898620
  object_id: d1f87609-056e-495a-65aa-c726e991d52c
  sha: sha256:670c12f652db94cec0e527831a93aed37c042fc3d5450fb29a27c91bc6fbec86
