bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6052686
  object_id: 59554526-0625-42a8-4660-47fc2e6e8dae
  sha: sha256:59e30dd6f0c91aa004186474f7203974a954f10a47bfe52df87e21c41b3b64df
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5880391
  object_id: 54a905fe-6b82-4b7b-63b1-317408c927f4
  sha: sha256:2ca03056b8d3c0e4617653456adb86239198c5d8694dc59d0e2c6976ec4c9876
