bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070140
  object_id: b87f0a5e-4687-4b1b-754a-bf9797c3b1d9
  sha: sha256:3bf5089f40054b2ffd22f8434a6c97742ae193a67888045e512a5328a3e7ab1e
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5897774
  object_id: f52191c8-b325-44b6-7c8c-ed57337235da
  sha: sha256:9f1a1fd383f7e7dd0f3b30eaff0107e91b6a020963192588f9072cf47ed49909
