bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6052761
  object_id: fec037ac-d3ef-48d8-7e78-d05e06c66161
  sha: sha256:47002be11873d607fede189d2fb329aca5a9306e1198c79addfae99c61143daa
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5880443
  object_id: c23cea9c-9784-41b8-4e7b-d828285ff804
  sha: sha256:1256f62f432fe59d718fe2cdb5938ad703898e8d8364c7e9d79abece4c07e427
