bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6052738
  object_id: 1f80ad52-2d25-45fe-50e6-8d51b8516662
  sha: sha256:7667ce3ac89f9643a98aec6eb068c18f0d33c7b40329ffb6eb089a3b5daee815
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5880448
  object_id: 3f84002c-f3e0-4c8b-60ea-f8fa209b508c
  sha: sha256:6800bea025b532db52eb5bc48131a999592a7d775dd6823ff0d8514f04810399
