bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070301
  object_id: 23f4c30c-e457-428b-6ef9-dc0d36212669
  sha: sha256:051fd513cfa58381e10cbe2478c07c8371c6c785b402b6c84f20ea198e229ba6
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5898625
  object_id: 585b1480-adb7-4ed9-4587-50b855012c5d
  sha: sha256:ad9c566e84d56b860fbe17552f730407d2f417f4cefaae8103e2bcfcdebea987
