bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070304
  object_id: 99f7a325-ac6a-4b65-723c-c2a75aff5d1f
  sha: sha256:bc1d2b337111ba99437f82f6300204be3fe1c3ed3a4bc1fe67727f998881b4ff
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5898631
  object_id: 40be67cd-b178-4389-426c-c2ffd1068f1d
  sha: sha256:b1deb1706565d24890e90dd352b0aca3dc930b7d2501010aa6c8280ed8d54412
