bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070303
  object_id: 7d67ac03-18ed-4916-6207-6ee4cf45fcb5
  sha: sha256:8e215667b39705a9ac0d9b611259fc27ebc682e38b4b0ca7a1946aba09474e95
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5898631
  object_id: c02bdb92-4dd8-45b0-5a8b-132ab3138d3b
  sha: sha256:a9f04763583aaafe122e4289fd2fc34645235aa674505d7b7e4fe28ec24a6a25
