bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070306
  object_id: 4e9a017f-3c9c-4419-63ef-6d96e773091e
  sha: sha256:0028fee4d5288060ad4d6736696ff3a5244153c3ec12d64265de465465ea681b
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5898620
  object_id: 6b45d1f0-94cb-4098-51d6-69cf604c5047
  sha: sha256:cfe1f896f2b899fa61b4735cbeead24f1d2d266e3ab59c4fe3d10a99768e119a
