bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6052751
  object_id: c08b1fc8-b196-4f6a-5597-8f1fc6409c2a
  sha: sha256:e0681cca249d55499404d78d0d5cb74862871db18c7c9e351f5a3c5bfc8aaa4a
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5880448
  object_id: b1fe01c2-5df2-43b1-7272-6c3d6a47fb1f
  sha: sha256:f0412c49d4a98092c950ebf2a602229a2e81668faf8ee04002490680fc018e9c
