bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070139
  object_id: 17fee596-65b2-4afa-74ac-157b0bfcc9b8
  sha: sha256:db15a249af766dc3b55066ef4eccbbf8d339c265697f90625d4535967983494f
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5897769
  object_id: e0fccfd7-852e-4942-5753-61c942f71a1a
  sha: sha256:aae642071bae27932b27ae2c0854ec5ff97dba61a94df6eff05d3cda0c215f5f
