bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070303
  object_id: 8e7584a9-1a56-443b-6082-d1a602696c1a
  sha: sha256:aeb6c1090a6c9862d9e47a5353b701ef024297470b48155c7eba029872a470a9
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5898637
  object_id: db7a1434-ed00-4249-7fde-d1f8e15f2acb
  sha: sha256:a45538994877c66dfa1fd56d5b43a959b1ca8b6d1fd4312afc89ff317de29ab2
