bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6052753
  object_id: 7a3eba3c-1773-4d24-77e3-91fbd7977cc6
  sha: sha256:28d643f696371e36d5e5a0a4ed108b551b9a9d364f91edb10c0e027f82d40776
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5880447
  object_id: 1ccf429e-77b0-4817-6e57-063c4a73b112
  sha: sha256:1f4b954788d5c873949b07939005a893b9415b9fd9a2de359a38737ff8ac4060
