bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070139
  object_id: 2c777393-ded7-4795-560b-520a7fe6aff0
  sha: sha256:97222f2203e9480ad9bfebb5ff32de2ce46b1d5d50ad080e5463594924022968
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5897773
  object_id: 1104cb92-af5b-46f9-4680-07978a75c5e1
  sha: sha256:2230f6bac223f67190e6b70094844076a3d58196871c9bd46098a4c52b18d9f0
