bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070305
  object_id: b8696e78-1aef-4491-540d-38a664add624
  sha: sha256:b4c2df8e5fb615c2c06ee305bcdb04ec1a77c4bc71ae7bad1a34d004c2ba2d53
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5898625
  object_id: 1f3db90c-5ea8-484f-6e4c-e91c2d59e693
  sha: sha256:1a61ca33cdeaf3a901f636f2cd5bee2fc90a6d420c8431684ee2ce01db54df20
