bosh-cpi-cloudstack_darwin.tar.gz:
  size: 6070303
  object_id: af71e873-b9e1-4dc8-7bcc-42baf677329b
  sha: sha256:f9bf4d29cbb85f4a50ec3ff7c835bc369930e180f8b5d76c8edd14d6e7253e35
bosh-cpi-cloudstack_linux.tar.gz:
  size: 5898622
  object_id: cdb7a569-3f1f-410d-54e5-2334b822781c
  sha: sha256:0a9a2c98a9b1b46d7fcc27e69ca52786abbeb99a7fdd501176703feca4a0dacb
